version: '3'

services:
  spring-backend:
    container_name: spring-backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/beeple"
    ports:
      - "8080:8080"
    networks:
      - vega-network
  venus-mysql:
    container_name: venus-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=venus
      - MYSQL_USER=venus
      - MYSQL_PASSWORD=venus
    ports:
      - "3306:3306"
    networks:
      - vega-network
networks:
  vega-network:
    external: true
